apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
  labels:
    app: vue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      name: vue-app
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app
          image: nginx:1.29-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      